"""Generate sources.yaml entries from a running wewe-rss instance.

Workflow:
    1. cd deploy/wewe-rss && docker compose up -d
    2. open http://localhost:4000 → 扫码 + 订阅公众号
    3. python scripts/wewe_feeds_to_yaml.py
    4. Paste the printed yaml block into config/sources.yaml

Reads WEWE_PORT + WEWE_AUTH_CODE from deploy/wewe-rss/.env.

Strategy: try OPML export first (standard, stable), fall back to /api/feeds
JSON if needed. Prints ready-to-paste yaml; does NOT modify sources.yaml.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / "deploy" / "wewe-rss" / ".env"


def _load_env() -> tuple[int, str]:
    if not ENV_PATH.exists():
        sys.stderr.write(
            f"ERROR: {ENV_PATH} missing — run setup first:\n"
            "  cd deploy/wewe-rss && cp .env.example .env (or generate via openssl rand -hex 32)\n"
        )
        sys.exit(2)
    port = 4000
    auth_code = ""
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        k, _, v = line.partition("=")
        if k == "WEWE_PORT":
            try:
                port = int(v)
            except ValueError:
                pass
        elif k == "WEWE_AUTH_CODE":
            auth_code = v.strip()
    if not auth_code:
        sys.stderr.write("ERROR: WEWE_AUTH_CODE not set in .env\n")
        sys.exit(2)
    return port, auth_code


def _slugify(name: str) -> str:
    """Turn a Chinese display name into a sources.yaml id (kebab-ish)."""
    # Strip punctuation, transliterate-light: just romanize when possible.
    # If no ascii letters survive, fall back to a hash-ish prefix.
    ascii_part = re.sub(r"[^a-zA-Z0-9]", "_", name).strip("_").lower()
    if ascii_part:
        return ascii_part
    # No ASCII at all — use first 4 chars unicode codepoints joined.
    return "wechat_" + "".join(f"{ord(c):x}" for c in name[:4])


def _emit_entry(*, slug: str, display_name: str, url: str) -> str:
    return (
        f"  - id: {slug}\n"
        f"    display_name: {display_name}\n"
        f"    fetcher_type: rss\n"
        f"    config:\n"
        f"      url: {url}\n"
        f"      max_items: 30\n"
        f"    enabled: false   # 改 true 启用\n"
    )


def _list_feeds(port: int, auth_code: str) -> list[tuple[str, str]] | None:
    """Hit GET /feeds/ which returns JSON list of subscribed mp accounts.

    Verified against wewe-rss v2.6.1 (cooderl/wewe-rss-sqlite). Each item:
      {id: "MP_WXS_...", name: "...", intro: "...", cover: "...", ...}

    Returns list of (display_name, atom_url_with_auth) or None on failure.
    """
    url = f"http://localhost:{port}/feeds/"
    try:
        r = httpx.get(url, timeout=10.0)
    except httpx.RequestError:
        return None
    if r.status_code != 200:
        return None
    try:
        body = r.json()
    except ValueError:
        return None
    if not isinstance(body, list):
        return None
    feeds: list[tuple[str, str]] = []
    for it in body:
        if not isinstance(it, dict):
            continue
        name = it.get("name") or it.get("mpName")
        feed_id = it.get("id")
        if not name or not feed_id:
            continue
        # Emit env-var placeholder, not the literal auth_code, so the yaml is
        # safe to commit. run_fetch.py expands ${WEWE_AUTH_CODE} at runtime.
        atom = f"http://localhost:{port}/feeds/{feed_id}.atom?auth_code=${{WEWE_AUTH_CODE}}"
        feeds.append((name, atom))
    return feeds or None


def main() -> None:
    port, auth_code = _load_env()
    feeds = _list_feeds(port, auth_code)
    if not feeds:
        sys.stderr.write(
            f"FAILED: GET http://localhost:{port}/feeds/ returned no subscriptions.\n"
            "Check that wewe-rss is running and you've added at least one 公众号 in the UI.\n"
        )
        sys.exit(1)
    print(f"# auto-generated by scripts/wewe_feeds_to_yaml.py — {len(feeds)} feed(s)")
    print("# Paste under `sources:` in config/sources.yaml; flip enabled to true.")
    print()
    seen_slugs: set[str] = set()
    for name, url in feeds:
        slug = _slugify(name) or "wechat"
        # Disambiguate duplicates.
        base, n = slug, 1
        while slug in seen_slugs:
            n += 1
            slug = f"{base}_{n}"
        seen_slugs.add(slug)
        print(_emit_entry(slug=slug, display_name=name, url=url))


if __name__ == "__main__":
    main()
